server:
  error:
    include-message: always
  port: 8080

app:
  datasource:
    jdbc-url: jdbc:postgresql://172.19.37.135:5432/fcc_alert
    username: fcc
    password: fcc@welab
    pool-size: 30

application:
  jwt:
    secretKey: kYp3s6v8y/B?E(H+MbQeThWmZq4t7w!z$C&F)J@NcRfUjXn2r5u8x/A?D*G-KaPdSgVkYp3s6v9y$B&E)H+MbQeThWmZq4t7w!z%C*F-JaNcRfUjXn2r5u8x/A?D(G+K
    tokenPrefix: Bearer
    tokenExpirationAfterMinutes: 120

